### ISSUE TITLE
Peer-to-Peer code review

### ISSUE THREAD

**Issue by zieeco** [AkshithaReddy1899/Microverse-Leader-Board#4]
Hi @AkshithaReddy1899 :cactus: 
Good job on your project. It looks nice and your user interface looks really appealing to the eyes. :100: 

<img src="https://media0.giphy.com/media/l3V0lsGtTMSB5YNgc/giphy.gif"/>

However, there are some issues you need to address in order to make it work better. 
Please refer to our suggestion below.

- In order to improve your user experience, please update your display so a user will see their score immediately they add a score instead of having to reload after adding a score to see their scores 
- It could be better to move your title to the left according to the wireframe 
- Your refresh button should not reload the whole page instead it should only call from your API
- You should try and filter your leader board not to add a bigger number, like give it a maximum number for the score

Cheers and Happy Coding!
Keep up with the great job :pray:

**Comment by AkshithaReddy1899** [comment]
Thank you so much for the review. I will make the changes as soon as possible
