### ISSUE TITLE
Peer-to-Peer Review

### ISSUE THREAD

**Issue by AdornChoga** [AkshithaReddy1899/Microverse-Leader-Board#5]
Congratulations on such a great job 💯.

- [x] Used best practices.
- [x] Good use of modules.
- [x] Layout looks great.
- [x] Code base looks clean.
- [x] Nice styling.

Suggested changes:

1. We think it would be nice to validate the user input.
2. We suggest that you only use blank lines to separate large or logical code blocks and remove them from [here](https://github.com/AkshithaReddy1899/Microverse-Leader-Board/blob/development/src/module/add.js#L6).
3. We think it would be nice to use an html template [here](https://github.com/AkshithaReddy1899/Microverse-Leader-Board/blob/development/src/module/render.js#L4-L22) to make it easy to for other developers to maintain the rendered html.

**Comment by AkshithaReddy1899** [comment]
Thank you for the suggestions. I will try to implement as soon as possible
